// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBlqLRHliwmUEd3O4zK_vojKOTEDBqTOU',
    appId: '1:806780929060:web:df5ebdc8faec6af3d344b1',
    messagingSenderId: '806780929060',
    projectId: 'future-navigator-demo-as',
    authDomain: 'future-navigator-demo-as.firebaseapp.com',
    databaseURL: 'https://future-navigator-demo-as-default-rtdb.firebaseio.com',
    storageBucket: 'future-navigator-demo-as.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-dOe8qkcQ-l3TAaIRf0S7loEbWem-fbE',
    appId: '1:806780929060:android:f32d280d3fc6870cd344b1',
    messagingSenderId: '806780929060',
    projectId: 'future-navigator-demo-as',
    databaseURL: 'https://future-navigator-demo-as-default-rtdb.firebaseio.com',
    storageBucket: 'future-navigator-demo-as.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV87jEvRVWDRyWFrik1_qxYKalFdCqvvU',
    appId: '1:806780929060:ios:1cc63fd226df4e35d344b1',
    messagingSenderId: '806780929060',
    projectId: 'future-navigator-demo-as',
    databaseURL: 'https://future-navigator-demo-as-default-rtdb.firebaseio.com',
    storageBucket: 'future-navigator-demo-as.firebasestorage.app',
    iosClientId: '806780929060-t5ood8g79e0q82ledhvja79hmvhktm0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.finspan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV87jEvRVWDRyWFrik1_qxYKalFdCqvvU',
    appId: '1:806780929060:ios:1cc63fd226df4e35d344b1',
    messagingSenderId: '806780929060',
    projectId: 'future-navigator-demo-as',
    databaseURL: 'https://future-navigator-demo-as-default-rtdb.firebaseio.com',
    storageBucket: 'future-navigator-demo-as.firebasestorage.app',
    iosClientId: '806780929060-t5ood8g79e0q82ledhvja79hmvhktm0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.finspan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBlqLRHliwmUEd3O4zK_vojKOTEDBqTOU',
    appId: '1:806780929060:web:086c3486fa9ec893d344b1',
    messagingSenderId: '806780929060',
    projectId: 'future-navigator-demo-as',
    authDomain: 'future-navigator-demo-as.firebaseapp.com',
    databaseURL: 'https://future-navigator-demo-as-default-rtdb.firebaseio.com',
    storageBucket: 'future-navigator-demo-as.firebasestorage.app',
  );
}
